steps:

- script: |
    sudo -iEH -u ruby bash -c "cd $(Build.SourcesDirectory) && bin/rake spec:deps"

  displayName: Install dependencies

- script: |
    sudo -iEH -u ruby bash -c "cd $(Build.SourcesDirectory) && bin/rake spec:rubygems:clone_rubygems_v3.0.3"

  displayName: Clone rubygems

- script: |
    sudo -iEH -u ruby bash -c "cd $(Build.SourcesDirectory) && gem install --no-document --conservative rspec_junit_formatter"

  displayName: Install test results formatter

- script: |
    sudo -iEH -u ruby bash -c "cd $(Build.SourcesDirectory) && ruby -r rspec_junit_formatter bin/rspec --format progress --format RspecJunitFormatter -o rspec/bundler-junit-results.xml"

  displayName: Run specs

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: rspec/bundler-junit-results.xml
  displayName: Publish test results
  condition: succeededOrFailed()
